DEFAULT_SEGMENT_START_SECONDS = 0.0
DEFAULT_SEGMENT_END_SECONDS = 0.0
DEFAULT_ENTITY_CONFIDENCE = 0.0
DEFAULT_LOCAL_USER_ID = "local_user"

JOB_STATUS_PENDING = "pending"
JOB_STATUS_PROCESSING = "processing"
JOB_STATUS_REVIEW = "review"
JOB_STATUS_CONFIRMED = "confirmed"
JOB_STATUS_EXPORTED = "exported"
JOB_STATUS_FAILED = "failed"

SEGMENT_REVIEW_STATUS_PENDING = "pending"
SEGMENT_REVIEW_STATUS_CONFIRMED = "confirmed"

ANALYSIS_STATUS_PENDING = "pending"
ANALYSIS_STATUS_CURRENT = "current"
ANALYSIS_STATUS_STALE = "stale"
ANALYSIS_STATUS_FAILED = "failed"

EVIDENCE_SOURCE_SPECIALIZED_MODEL = "specialized_model"
EVIDENCE_SOURCE_AUDIO_ANALYSIS = "audio_analysis"
EVIDENCE_SOURCE_OCR = "ocr"
EVIDENCE_SOURCE_LLM = "llm"
EVIDENCE_SOURCE_HUMAN_REVIEW = "human_review"

EVIDENCE_AVAILABILITY_AVAILABLE = "available"
EVIDENCE_AVAILABILITY_UNAVAILABLE = "unavailable"
EVIDENCE_AVAILABILITY_FAILED = "failed"

REVIEW_OPERATION_TEXT_EDIT = "text_edit"
REVIEW_OPERATION_SPEAKER_EDIT = "speaker_edit"
REVIEW_OPERATION_SPLIT = "split"
REVIEW_OPERATION_MERGE = "merge"
REVIEW_OPERATION_DELETE = "delete"
REVIEW_OPERATION_CONFIRM = "confirm"

EXPORT_FORMAT_JSON = "json"
EXPORT_FORMAT_MARKDOWN = "markdown"
